name: Multiple shells commands

on:
  push:
    branches:
      - "main"
  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    shell: python
    steps:
      - name: python commands
        run: |
          import platform
          print(platform.processor())

  run-windows-command:
    runs-on: windows-latest
    needs: ["run-shell-command"]
    steps:
      - name: current directory with powershell
        run: Get-Location
      - name: current directory with bash
        run: pwd
